version: "3.9"

services:
  # Flask App
  app:
    build: .
    container_name: flask-app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:1234@localhost/flask_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
