"""add last_login and last_logged_out to user table

Revision ID: 2a481bd891a1
Revises: c054669cb412
Create Date: 2025-05-09 23:39:21.951426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a481bd891a1'
down_revision = 'c054669cb412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_logged_out', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_logged_out')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
