"""create book and category table

Revision ID: 8d47edccde61
Revises: d61f77494c2a
Create Date: 2025-05-05 11:04:04.779123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d47edccde61'
down_revision = 'd61f77494c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', name='user_role'),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'),
               type_=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', name='user_role'),
               existing_nullable=False)

    op.drop_table('books')
    op.drop_table('categories')
    # ### end Alembic commands ###
